// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM_Er5Hm8IBoxHTAF41typIWiFIQg6ekM',
    appId: '1:102324667336:web:2dab87f9a0fc62ef2ab6fd',
    messagingSenderId: '102324667336',
    projectId: 'travelagency-643c2',
    authDomain: 'travelagency-643c2.firebaseapp.com',
    storageBucket: 'travelagency-643c2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhX4gicEj0pUYDjeQK-I5wvPiNTBdFc74',
    appId: '1:102324667336:android:dfeae82587493c442ab6fd',
    messagingSenderId: '102324667336',
    projectId: 'travelagency-643c2',
    storageBucket: 'travelagency-643c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASqLxrbXs5fx4mJpds1b7QDRnREJWBiAQ',
    appId: '1:102324667336:ios:4c5370d8df6fb3f02ab6fd',
    messagingSenderId: '102324667336',
    projectId: 'travelagency-643c2',
    storageBucket: 'travelagency-643c2.firebasestorage.app',
    iosBundleId: 'com.example.travelagency',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASqLxrbXs5fx4mJpds1b7QDRnREJWBiAQ',
    appId: '1:102324667336:ios:4c5370d8df6fb3f02ab6fd',
    messagingSenderId: '102324667336',
    projectId: 'travelagency-643c2',
    storageBucket: 'travelagency-643c2.firebasestorage.app',
    iosBundleId: 'com.example.travelagency',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM_Er5Hm8IBoxHTAF41typIWiFIQg6ekM',
    appId: '1:102324667336:web:8587f6d7a40f04bf2ab6fd',
    messagingSenderId: '102324667336',
    projectId: 'travelagency-643c2',
    authDomain: 'travelagency-643c2.firebaseapp.com',
    storageBucket: 'travelagency-643c2.firebasestorage.app',
  );

}